files:
  - source: src/assests/lang/*.json
    translation: test.json
targets:
  - name: test
    sources:
      - src/assests/lang /*.json
    file: /%original_path%/%locale_with_underscore%.xliff
    format: xliff
    labels:
      - translatable
